### ISSUE TITLE
Add Constraints 1.3 SQL File needs attention

### ISSUE THREAD

**Issue by Ferrisx4** [NAL-i5K/T2-to-T3-Upgrade-Guide#9]
This script attempts to re-add primary keys and other constraints to the Chado 1.3 database schema that are not preserved during the Chado upgrade via Tripal. 

Currently it adds seemingly most of them but it might not have complete coverage and also tries to add a lot of constraints that already exist.

**Comment by mpoelchau** [comment]
Upgrade to T3 is complete.
